# Workflow para desplegar contenido estático en GitHub Pages
name: Deploy static content to Pages

on:
  # Corre en push a la rama main
  push:
    branches: ['main']

  # Permite ejecución manual desde Actions
  workflow_dispatch:

# Permisos para usar GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Control de concurrencia
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # ✅ Copiar vistas a dist antes del despliegue
      - name: Copy views to dist
        run: cp -r ./src/views ./dist/src/views

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
